# Generated by Django 5.2.11 on 2026-02-23 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='recurso',
        ),
    ]
